[package]
name = "safe_dlls"
version = "0.1.0"
authors = ["Natalie Popescu <nataliepopescu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencher = "0.1.5"

[[bench]]
name = "bench"
harness = false
